# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/riscv/contest_Etienne/fpga/constraints/zybo_z7_20.xdc

# XDC: /home/riscv/contest_Etienne/fpga/constraints/cva6_fpga.xdc

# IP: /home/riscv/contest_Etienne/fpga/xilinx/xlnx_processing_system7/ip/xlnx_processing_system7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_processing_system7 || ORIG_REF_NAME==xlnx_processing_system7} -quiet] -quiet

# IP: /home/riscv/contest_Etienne/fpga/xilinx/xlnx_clk_gen/ip/xlnx_clk_gen.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_clk_gen || ORIG_REF_NAME==xlnx_clk_gen} -quiet] -quiet

# IP: /home/riscv/contest_Etienne/fpga/xilinx/xlnx_axi_dwidth_converter_dm_master/ip/xlnx_axi_dwidth_converter_dm_master.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter_dm_master || ORIG_REF_NAME==xlnx_axi_dwidth_converter_dm_master} -quiet] -quiet

# IP: /home/riscv/contest_Etienne/fpga/xilinx/xlnx_axi_dwidth_converter_dm_slave/ip/xlnx_axi_dwidth_converter_dm_slave.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xlnx_axi_dwidth_converter_dm_slave || ORIG_REF_NAME==xlnx_axi_dwidth_converter_dm_slave} -quiet] -quiet
